# Generated by Django 3.1.2 on 2020-12-05 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whytolearn',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='translation',
            name='sentence_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Main_Language', to='language.language', verbose_name='Main Language'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translate_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Translate_Language', to='language.language', verbose_name='Translate Language'),
        ),
        migrations.AddField(
            model_name='languagelevels',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language'),
        ),
        migrations.AddField(
            model_name='langtolearn',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='language.language'),
        ),
        migrations.AddField(
            model_name='langtolearn',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='languagelevels',
            unique_together={('language_id', 'level_num')},
        ),
        migrations.AlterUniqueTogether(
            name='langtolearn',
            unique_together={('user_id', 'language_id', 'user_type')},
        ),
    ]
